name: Build bibleart nextjs app
on: push
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    # Install npm dependencies
    - name: Install npm dependencies
      run: npm install
    # Run npm build
    - name: Build project assets
      run: npm run build
    # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bibleart
        path: .next/
